#!/bin/bash

#borra -r //fichero -r restaura (si existe) el fichero llamado "fichero"

#Si el comando para restaurar está en primer lugar
if [ $1 = "-r" ]
then

#nos situamos sobre el directorio en el que tenemos la papelera, 
#en este caso:
cd /home/smarrero/borra

echo "Se va a restaurar el fichero $2 ..."
#comprobamos si existe, si es así:
if [ -e $2 ]
then 
#movemos el fichero al directorio en el que se encontraba originalmente,
#en este caso:
sudo mv $2 /home/smarrero/Documentos

echo "Archivo restaurado con éxito"

#si no existe
else 
echo "El fichero $2 no existe o no se encuentra en la papelera"
fi
#si el comando para restaurar está en segundo lugar
elif [ $2 = "-r" ] 
then
echo "Se va a restaurar el fichero $1 ..."

#nos situamos sobre el directorio de la papelera
cd /home/smarrero/borra

#comprobamos la existencia del fichero
if [ -e $1 ]
then
#movemos el fichero al directorio original
sudo mv $1 /home/smarrero/Documentos

echo "Archivo restaurado con éxito"
else
#si el fichero no existe
echo "El fichero $1 no existe o no se encuentra en la papelera"
fi
fi
 

